/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsEditIdRouteImport } from './routes/admin.products.edit.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsEditIdRoute = AdminProductsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wishlist': typeof WishlistRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/edit/$id': typeof AdminProductsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/products'
    | '/admin/products/new'
    | '/admin/products/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/products'
    | '/admin/products/new'
    | '/admin/products/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/contact'
    | '/sitemap.xml'
    | '/wishlist'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/products'
    | '/admin/products/new'
    | '/admin/products/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/edit/$id': {
      id: '/admin/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/products/edit/$id'
      preLoaderRoute: typeof AdminProductsEditIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsEditIdRoute: typeof AdminProductsEditIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsEditIdRoute: AdminProductsEditIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
